-- Supabase PostgreSQL schema for the shuttle route management project.
-- Run this file in Supabase SQL Editor. It intentionally does not create a database.

BEGIN;

DROP TABLE IF EXISTS route_plan_logs CASCADE;
DROP TABLE IF EXISTS route_plan_driver_assignments CASCADE;
DROP TABLE IF EXISTS route_plan_vehicle_assignments CASCADE;
DROP TABLE IF EXISTS route_plan_customers CASCADE;
DROP TABLE IF EXISTS route_plans CASCADE;
DROP TABLE IF EXISTS import_logs CASCADE;
DROP TABLE IF EXISTS source_metadata CASCADE;
DROP TABLE IF EXISTS external_vehicles CASCADE;
DROP TABLE IF EXISTS external_drivers CASCADE;
DROP TABLE IF EXISTS external_customers CASCADE;
DROP TABLE IF EXISTS TheoDoiTrangThai CASCADE;
DROP TABLE IF EXISTS ChiTietLoTrinh CASCADE;
DROP TABLE IF EXISTS LoTrinhTrungChuyen CASCADE;
DROP TABLE IF EXISTS VeTrungChuyen CASCADE;
DROP TABLE IF EXISTS KhachHang CASCADE;
DROP TABLE IF EXISTS XeTrungChuyen CASCADE;
DROP TABLE IF EXISTS TaiXe CASCADE;
DROP TABLE IF EXISTS NhanVienDieuPhoi CASCADE;
DROP TABLE IF EXISTS TaiKhoanNguoiDung CASCADE;

CREATE TABLE TaiKhoanNguoiDung (
  MaTaiKhoan integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TenDangNhap varchar(50) NOT NULL UNIQUE,
  MatKhauMaHoa varchar(255) NOT NULL,
  SoDienThoai varchar(15) NULL,
  VaiTro varchar(30) NULL,
  TrangThaiTaiKhoan boolean NOT NULL DEFAULT TRUE,
  YeuCauDoiMatKhau boolean NOT NULL DEFAULT FALSE,
  SoLanDangNhapSai integer NOT NULL DEFAULT 0,
  KhoaTamThoiDenLuc timestamp NULL,
  NgayTao timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE NhanVienDieuPhoi (
  MaNhanVien integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  HoTen varchar(100) NOT NULL,
  SoDienThoai varchar(15) NULL,
  TrangThai varchar(30) NULL,
  MaTaiKhoan integer NULL REFERENCES TaiKhoanNguoiDung(MaTaiKhoan)
);

CREATE TABLE TaiXe (
  MaTaiXe integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  MaNhanVienTaiXe varchar(20) NULL,
  HoTen varchar(100) NOT NULL,
  SoDienThoai varchar(15) NOT NULL UNIQUE,
  CCCD varchar(20) NOT NULL UNIQUE,
  LoaiBangLai varchar(50) NULL,
  TrangThaiTaiXe varchar(30) NULL,
  MaTaiKhoan integer NULL REFERENCES TaiKhoanNguoiDung(MaTaiKhoan)
);

CREATE TABLE XeTrungChuyen (
  MaXe integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  BienSo varchar(50) NOT NULL UNIQUE,
  LoaiXe varchar(50) NOT NULL,
  SoCho integer NOT NULL,
  TrangThaiXe varchar(30) NULL,
  CONSTRAINT ck_xetrungchuyen_socho CHECK (SoCho BETWEEN 4 AND 45)
);

CREATE TABLE KhachHang (
  MaKhachHang integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TenKhachHang varchar(100) NOT NULL,
  SoDienThoai varchar(15) NOT NULL UNIQUE,
  DiaChiDon varchar(255) NOT NULL,
  DiaChiDonLat numeric(10,7) NULL,
  DiaChiDonLng numeric(10,7) NULL,
  DiaChiTra varchar(255) NOT NULL,
  DiaChiTraLat numeric(10,7) NULL,
  DiaChiTraLng numeric(10,7) NULL,
  TrangThai varchar(30) NULL
);

CREATE TABLE VeTrungChuyen (
  MaVe integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  KhungGioTrungChuyen varchar(100) NULL,
  SoLuongGhe integer NOT NULL,
  TrangThaiVe varchar(50) NOT NULL,
  MaKhachHang integer NOT NULL REFERENCES KhachHang(MaKhachHang),
  CONSTRAINT ck_vetrungchuyen_soluongghe CHECK (SoLuongGhe BETWEEN 1 AND 10)
);

CREATE TABLE LoTrinhTrungChuyen (
  MaLoTrinh integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ThoiGianBatDau timestamp NOT NULL,
  ThoiGianKetThuc timestamp NULL,
  LoTrinhDuKien text NULL,
  GhiChu text NULL,
  TrangThaiLoTrinh varchar(50) NOT NULL,
  MaXe integer NOT NULL REFERENCES XeTrungChuyen(MaXe),
  MaTaiXe integer NOT NULL REFERENCES TaiXe(MaTaiXe),
  MaNhanVien integer NOT NULL REFERENCES NhanVienDieuPhoi(MaNhanVien),
  CONSTRAINT ck_lotrinh_thoigian CHECK (ThoiGianKetThuc IS NULL OR ThoiGianKetThuc >= ThoiGianBatDau)
);

CREATE TABLE ChiTietLoTrinh (
  MaChiTiet integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ThuTuDonTra integer NOT NULL,
  DiemDon varchar(255) NOT NULL,
  DiemDonLat numeric(10,7) NULL,
  DiemDonLng numeric(10,7) NULL,
  DiemTra varchar(255) NOT NULL,
  DiemTraLat numeric(10,7) NULL,
  DiemTraLng numeric(10,7) NULL,
  ThoiGianDonDuKien timestamp NULL,
  TrangThaiKhach varchar(50) NULL,
  MaLoTrinh integer NOT NULL REFERENCES LoTrinhTrungChuyen(MaLoTrinh),
  MaVe integer NOT NULL REFERENCES VeTrungChuyen(MaVe)
);

CREATE TABLE TheoDoiTrangThai (
  MaTheoDoi integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ViTriHienTai varchar(255) NULL,
  ThoiDiemCapNhat timestamp NOT NULL DEFAULT NOW(),
  TrangThai varchar(50) NULL,
  MaLoTrinh integer NOT NULL REFERENCES LoTrinhTrungChuyen(MaLoTrinh)
);

CREATE UNIQUE INDEX ux_taikhoannguoidung_sodienthoai
  ON TaiKhoanNguoiDung(SoDienThoai)
  WHERE SoDienThoai IS NOT NULL;

CREATE UNIQUE INDEX ux_taixe_manhanvientaixe
  ON TaiXe(MaNhanVienTaiXe)
  WHERE MaNhanVienTaiXe IS NOT NULL;

CREATE INDEX ix_lotrinh_taixe_trangthai_time
  ON LoTrinhTrungChuyen(MaTaiXe, TrangThaiLoTrinh, ThoiGianBatDau);

CREATE INDEX ix_lotrinh_xe_trangthai_time
  ON LoTrinhTrungChuyen(MaXe, TrangThaiLoTrinh, ThoiGianBatDau);

CREATE INDEX ix_ve_khachhang_trangthai
  ON VeTrungChuyen(MaKhachHang, TrangThaiVe);

CREATE INDEX ix_chitiet_lotrinh_thutu
  ON ChiTietLoTrinh(MaLoTrinh, ThuTuDonTra);

CREATE TABLE external_customers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_ma_khach_hang integer NOT NULL UNIQUE,
  customer_code varchar(20) NOT NULL UNIQUE,
  full_name varchar(100) NOT NULL,
  phone varchar(15) NOT NULL UNIQUE,
  default_pickup_address varchar(255) NULL,
  default_dropoff_address varchar(255) NULL,
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  is_active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_external_customers_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_external_customers_phone ON external_customers(phone);

CREATE TABLE external_drivers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_ma_tai_xe integer NOT NULL UNIQUE,
  driver_code varchar(20) NOT NULL UNIQUE,
  employee_code varchar(20) NULL,
  full_name varchar(100) NOT NULL,
  phone varchar(15) NOT NULL UNIQUE,
  national_id varchar(20) NOT NULL UNIQUE,
  license_no varchar(30) NULL,
  license_class varchar(50) NULL,
  work_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  availability_status varchar(20) NOT NULL DEFAULT 'AVAILABLE',
  is_active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_external_drivers_work_status CHECK (work_status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT ck_external_drivers_availability CHECK (availability_status IN ('AVAILABLE', 'ASSIGNED', 'BUSY', 'OFF'))
);

CREATE UNIQUE INDEX ux_external_drivers_employee_code
  ON external_drivers(employee_code)
  WHERE employee_code IS NOT NULL;

CREATE INDEX ix_external_drivers_availability_status ON external_drivers(availability_status);

CREATE TABLE external_vehicles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_ma_xe integer NOT NULL UNIQUE,
  vehicle_code varchar(20) NOT NULL UNIQUE,
  plate_number varchar(20) NOT NULL UNIQUE,
  vehicle_type varchar(50) NULL,
  capacity integer NOT NULL,
  seat_count integer NOT NULL,
  operational_status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  availability_status varchar(20) NOT NULL DEFAULT 'AVAILABLE',
  is_active boolean NOT NULL DEFAULT TRUE,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_external_vehicles_capacity CHECK (capacity > 0),
  CONSTRAINT ck_external_vehicles_seat_count CHECK (seat_count > 0),
  CONSTRAINT ck_external_vehicles_operational CHECK (operational_status IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT ck_external_vehicles_availability CHECK (availability_status IN ('AVAILABLE', 'ASSIGNED', 'ON_TRIP', 'MAINTENANCE'))
);

CREATE INDEX ix_external_vehicles_availability_status ON external_vehicles(availability_status);

CREATE TABLE route_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_code varchar(30) NOT NULL UNIQUE,
  planned_start_at timestamp NOT NULL,
  planned_end_at timestamp NULL,
  status varchar(20) NOT NULL DEFAULT 'DRAFT',
  notes varchar(500) NULL,
  created_by varchar(50) NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_route_plans_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX ix_route_plans_planned_start_at ON route_plans(planned_start_at);

CREATE TABLE route_plan_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_plan_id bigint NOT NULL REFERENCES route_plans(id),
  external_customer_id integer NOT NULL REFERENCES external_customers(id),
  sequence_no integer NOT NULL,
  customer_code_snapshot varchar(20) NOT NULL,
  customer_name_snapshot varchar(100) NOT NULL,
  customer_phone_snapshot varchar(15) NOT NULL,
  pickup_address_snapshot varchar(255) NOT NULL,
  dropoff_address_snapshot varchar(255) NOT NULL,
  note varchar(255) NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_route_plan_customers_plan_sequence UNIQUE (route_plan_id, sequence_no),
  CONSTRAINT ck_route_plan_customers_sequence CHECK (sequence_no > 0)
);

CREATE INDEX ix_route_plan_customers_plan_seq ON route_plan_customers(route_plan_id, sequence_no);

CREATE TABLE route_plan_vehicle_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_plan_id bigint NOT NULL REFERENCES route_plans(id),
  external_vehicle_id integer NOT NULL REFERENCES external_vehicles(id),
  assignment_status varchar(20) NOT NULL DEFAULT 'SELECTED',
  assigned_at timestamp NOT NULL DEFAULT NOW(),
  vehicle_code_snapshot varchar(20) NOT NULL,
  vehicle_plate_snapshot varchar(20) NOT NULL,
  vehicle_type_snapshot varchar(50) NULL,
  vehicle_capacity_snapshot integer NOT NULL,
  vehicle_seat_count_snapshot integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_route_plan_vehicle_assignments_plan_vehicle UNIQUE (route_plan_id, external_vehicle_id),
  CONSTRAINT ck_route_plan_vehicle_assignments_status CHECK (assignment_status IN ('SELECTED', 'CONFIRMED', 'REPLACED'))
);

CREATE INDEX ix_route_plan_vehicle_assignments_plan ON route_plan_vehicle_assignments(route_plan_id);

CREATE TABLE route_plan_driver_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_plan_id bigint NOT NULL REFERENCES route_plans(id),
  external_driver_id integer NOT NULL REFERENCES external_drivers(id),
  route_plan_vehicle_assignment_id bigint NULL REFERENCES route_plan_vehicle_assignments(id),
  assignment_status varchar(20) NOT NULL DEFAULT 'SELECTED',
  assigned_at timestamp NOT NULL DEFAULT NOW(),
  driver_code_snapshot varchar(20) NOT NULL,
  driver_name_snapshot varchar(100) NOT NULL,
  driver_phone_snapshot varchar(15) NOT NULL,
  driver_national_id_snapshot varchar(20) NULL,
  driver_license_no_snapshot varchar(30) NULL,
  driver_license_class_snapshot varchar(50) NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_route_plan_driver_assignments_plan_driver UNIQUE (route_plan_id, external_driver_id),
  CONSTRAINT ck_route_plan_driver_assignments_status CHECK (assignment_status IN ('SELECTED', 'CONFIRMED', 'REPLACED'))
);

CREATE INDEX ix_route_plan_driver_assignments_plan ON route_plan_driver_assignments(route_plan_id);

CREATE TABLE source_metadata (
  source_system varchar(30) PRIMARY KEY,
  source_name varchar(100) NOT NULL,
  description varchar(255) NULL,
  last_import_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE import_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_system varchar(30) NOT NULL,
  entity_type varchar(30) NOT NULL,
  total_records integer NOT NULL DEFAULT 0,
  succeeded_records integer NOT NULL DEFAULT 0,
  failed_records integer NOT NULL DEFAULT 0,
  status varchar(20) NOT NULL DEFAULT 'SUCCESS',
  started_at timestamp NOT NULL DEFAULT NOW(),
  finished_at timestamp NULL,
  error_message text NULL
);

CREATE TABLE route_plan_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  route_plan_id bigint NOT NULL REFERENCES route_plans(id),
  event_type varchar(50) NOT NULL,
  message varchar(500) NULL,
  payload jsonb NULL,
  created_by varchar(50) NULL,
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_route_plan_logs_plan_time ON route_plan_logs(route_plan_id, created_at);

-- Demo accounts use bcrypt hash for password "123456".
WITH dispatcher_account AS (
  INSERT INTO TaiKhoanNguoiDung (TenDangNhap, MatKhauMaHoa, SoDienThoai, VaiTro, TrangThaiTaiKhoan)
  VALUES ('dieuphoi1', '$2b$10$OjQFSKCq23Kyh6oLUqnRUeJNx2Z/TWT7VtMIJrLMzq7ef9pRl7f/K', '0812345678', 'Nhân viên điều phối', TRUE)
  RETURNING MaTaiKhoan
)
INSERT INTO NhanVienDieuPhoi (HoTen, SoDienThoai, TrangThai, MaTaiKhoan)
SELECT 'Nhân viên điều phối 1', '0812345678', 'Hoạt động', MaTaiKhoan
FROM dispatcher_account;

WITH driver_account AS (
  INSERT INTO TaiKhoanNguoiDung (TenDangNhap, MatKhauMaHoa, SoDienThoai, VaiTro, TrangThaiTaiKhoan)
  VALUES ('taixe1', '$2b$10$OjQFSKCq23Kyh6oLUqnRUeJNx2Z/TWT7VtMIJrLMzq7ef9pRl7f/K', '0912345678', 'Tài xế', TRUE)
  RETURNING MaTaiKhoan
)
INSERT INTO TaiXe (MaNhanVienTaiXe, HoTen, SoDienThoai, CCCD, LoaiBangLai, TrangThaiTaiXe, MaTaiKhoan)
SELECT 'NVTX001', 'Nguyễn Minh Tuấn', '0912345678', '012345678901', 'B2', 'Rảnh', MaTaiKhoan
FROM driver_account;

INSERT INTO TaiXe (MaNhanVienTaiXe, HoTen, SoDienThoai, CCCD, LoaiBangLai, TrangThaiTaiXe, MaTaiKhoan)
VALUES
  ('NVTX002', 'Trần Văn Hùng', '0912345671', '012345678902', 'B2', 'Rảnh', NULL),
  ('NVTX003', 'Lê Thanh Nam', '0912345672', '012345678903', 'C', 'Đang thực hiện chuyến', NULL),
  ('NVTX004', 'Phạm Văn Long', '0912345673', '012345678904', 'B2', 'Rảnh', NULL),
  ('NVTX005', 'Hoàng Minh Đức', '0912345674', '012345678905', 'C', 'Đã phân công', NULL);

INSERT INTO XeTrungChuyen (BienSo, LoaiXe, SoCho, TrangThaiXe)
VALUES
  ('51A-12345', 'Xe 7 chỗ', 7, 'Rảnh'),
  ('51B-67890', 'Xe 4 chỗ', 4, 'Rảnh'),
  ('51C-11111', 'Xe 16 chỗ', 16, 'Rảnh'),
  ('51D-22222', 'Xe 7 chỗ', 7, 'Rảnh'),
  ('51E-33333', 'Xe 4 chỗ', 4, 'Rảnh');

INSERT INTO KhachHang (TenKhachHang, SoDienThoai, DiaChiDon, DiaChiDonLat, DiaChiDonLng, DiaChiTra, DiaChiTraLat, DiaChiTraLng, TrangThai)
VALUES
  ('Hà Văn Nam', '0389123456', '56 Chu Mạnh Trinh', 16.0612000, 108.2218000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động'),
  ('Nguyễn Thị Thuận', '0389123452', '36 Tú Quỳ', 16.0755000, 108.2422000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động'),
  ('Lê Minh Đại', '0981234567', '12 Nguyễn Văn Linh', 16.0548000, 108.2195000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động'),
  ('Phạm Thị Dung', '0912345670', '34 Lê Duẩn', 16.0710000, 108.2200000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động'),
  ('Trần Hoàng Bách', '0901234567', '56 Trần Phú', 16.0678000, 108.2245000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động'),
  ('Nguyễn Văn Phương', '0922333444', '78 Hùng Vương', 16.0695000, 108.2158000, 'Bến xe Đà Nẵng', 16.0677000, 108.1886000, 'Hoạt động');

INSERT INTO VeTrungChuyen (KhungGioTrungChuyen, SoLuongGhe, TrangThaiVe, MaKhachHang)
SELECT data.KhungGioTrungChuyen, data.SoLuongGhe, data.TrangThaiVe, kh.MaKhachHang
FROM (
  VALUES
    ('0389123456', '7:00 - 9:00', 1, 'Cần trung chuyển'),
    ('0389123452', '7:00 - 9:00', 2, 'Cần trung chuyển'),
    ('0981234567', '7:00 - 9:00', 1, 'Cần trung chuyển'),
    ('0912345670', '9:00 - 11:00', 1, 'Cần trung chuyển'),
    ('0901234567', '9:00 - 11:00', 2, 'Cần trung chuyển'),
    ('0922333444', '11:00 - 13:00', 1, 'Cần trung chuyển')
) AS data(SoDienThoai, KhungGioTrungChuyen, SoLuongGhe, TrangThaiVe)
JOIN KhachHang kh ON kh.SoDienThoai = data.SoDienThoai;

WITH route_seed AS (
  INSERT INTO LoTrinhTrungChuyen
    (ThoiGianBatDau, ThoiGianKetThuc, LoTrinhDuKien, GhiChu, TrangThaiLoTrinh, MaXe, MaTaiXe, MaNhanVien)
  SELECT
    NOW() + INTERVAL '1 hour',
    NULL,
    'Hải Châu -> Thanh Khê -> Bến xe Đà Nẵng',
    'Lộ trình demo',
    'Đang thực hiện',
    xe.MaXe,
    tx.MaTaiXe,
    nv.MaNhanVien
  FROM XeTrungChuyen xe
  CROSS JOIN TaiXe tx
  CROSS JOIN NhanVienDieuPhoi nv
  WHERE xe.BienSo = '51A-12345'
    AND tx.SoDienThoai = '0912345678'
  ORDER BY nv.MaNhanVien
  LIMIT 1
  RETURNING MaLoTrinh
),
ticket_seed AS (
  SELECT v.MaVe
  FROM VeTrungChuyen v
  JOIN KhachHang kh ON kh.MaKhachHang = v.MaKhachHang
  WHERE kh.SoDienThoai = '0389123456'
  ORDER BY v.MaVe
  LIMIT 1
)
INSERT INTO ChiTietLoTrinh
  (ThuTuDonTra, DiemDon, DiemDonLat, DiemDonLng, DiemTra, DiemTraLat, DiemTraLng, ThoiGianDonDuKien, TrangThaiKhach, MaLoTrinh, MaVe)
SELECT
  1,
  '56 Chu Mạnh Trinh',
  16.0612000,
  108.2218000,
  'Bến xe Đà Nẵng',
  16.0677000,
  108.1886000,
  NOW() + INTERVAL '1 hour',
  'Đã đến điểm đón',
  route_seed.MaLoTrinh,
  ticket_seed.MaVe
FROM route_seed
CROSS JOIN ticket_seed;

INSERT INTO TheoDoiTrangThai (ViTriHienTai, TrangThai, MaLoTrinh)
SELECT 'Đang tại khu vực Hải Châu', 'Đang thực hiện', MaLoTrinh
FROM LoTrinhTrungChuyen
ORDER BY MaLoTrinh
LIMIT 1;

INSERT INTO source_metadata (source_system, source_name, description, last_import_at)
VALUES ('SIMULATED', 'Dữ liệu ngoài (giả lập)', 'Master data mô phỏng cho đồ án', NOW());

INSERT INTO external_customers (
  legacy_ma_khach_hang,
  customer_code,
  full_name,
  phone,
  default_pickup_address,
  default_dropoff_address,
  status,
  is_active
)
SELECT
  kh.MaKhachHang,
  'KH' || LPAD(kh.MaKhachHang::text, 8, '0'),
  kh.TenKhachHang,
  kh.SoDienThoai,
  kh.DiaChiDon,
  kh.DiaChiTra,
  CASE WHEN kh.TrangThai IS NULL OR kh.TrangThai = 'Hoạt động' THEN 'ACTIVE' ELSE 'INACTIVE' END,
  CASE WHEN kh.TrangThai IS NULL OR kh.TrangThai = 'Hoạt động' THEN TRUE ELSE FALSE END
FROM KhachHang kh;

INSERT INTO external_drivers (
  legacy_ma_tai_xe,
  driver_code,
  employee_code,
  full_name,
  phone,
  national_id,
  license_no,
  license_class,
  work_status,
  availability_status,
  is_active
)
SELECT
  tx.MaTaiXe,
  CASE WHEN tx.MaTaiXe < 1000 THEN 'TX' || LPAD(tx.MaTaiXe::text, 3, '0') ELSE 'TX' || tx.MaTaiXe::text END,
  tx.MaNhanVienTaiXe,
  tx.HoTen,
  tx.SoDienThoai,
  tx.CCCD,
  NULL,
  tx.LoaiBangLai,
  CASE WHEN tx.TrangThaiTaiXe IN ('Ngừng hoạt động') THEN 'INACTIVE' ELSE 'ACTIVE' END,
  CASE
    WHEN tx.TrangThaiTaiXe IN ('Rảnh') THEN 'AVAILABLE'
    WHEN tx.TrangThaiTaiXe IN ('Đã phân công') THEN 'ASSIGNED'
    WHEN tx.TrangThaiTaiXe IN ('Đang thực hiện', 'Đang thực hiện chuyến') THEN 'BUSY'
    WHEN tx.TrangThaiTaiXe IN ('Không sẵn sàng', 'Ngừng hoạt động') THEN 'OFF'
    ELSE 'AVAILABLE'
  END,
  CASE WHEN tx.TrangThaiTaiXe IN ('Ngừng hoạt động') THEN FALSE ELSE TRUE END
FROM TaiXe tx;

INSERT INTO external_vehicles (
  legacy_ma_xe,
  vehicle_code,
  plate_number,
  vehicle_type,
  capacity,
  seat_count,
  operational_status,
  availability_status,
  is_active
)
SELECT
  xe.MaXe,
  CASE WHEN xe.MaXe < 1000 THEN 'XE' || LPAD(xe.MaXe::text, 3, '0') ELSE 'XE' || xe.MaXe::text END,
  xe.BienSo,
  xe.LoaiXe,
  xe.SoCho,
  xe.SoCho,
  CASE WHEN xe.TrangThaiXe IN ('Ngừng hoạt động') THEN 'INACTIVE' ELSE 'ACTIVE' END,
  CASE
    WHEN xe.TrangThaiXe IN ('Rảnh') THEN 'AVAILABLE'
    WHEN xe.TrangThaiXe IN ('Đã phân công') THEN 'ASSIGNED'
    WHEN xe.TrangThaiXe IN ('Đang chạy', 'Đang thực hiện') THEN 'ON_TRIP'
    WHEN xe.TrangThaiXe IN ('Bảo trì') THEN 'MAINTENANCE'
    ELSE 'AVAILABLE'
  END,
  CASE WHEN xe.TrangThaiXe IN ('Ngừng hoạt động') THEN FALSE ELSE TRUE END
FROM XeTrungChuyen xe;

WITH plan_seed AS (
  INSERT INTO route_plans (plan_code, planned_start_at, planned_end_at, status, notes, created_by)
  VALUES ('RP0001', NOW() + INTERVAL '2 hours', NOW() + INTERVAL '4 hours', 'CONFIRMED', 'Kế hoạch điều phối demo [legacy_route_id=1]', 'dieuphoi1')
  RETURNING id
),
customer_seed AS (
  SELECT ec.*, row_number() OVER (ORDER BY ec.id) AS seq
  FROM external_customers ec
  WHERE ec.phone IN ('0389123456', '0389123452')
),
vehicle_seed AS (
  SELECT * FROM external_vehicles WHERE plate_number = '51A-12345' LIMIT 1
),
driver_seed AS (
  SELECT * FROM external_drivers WHERE phone = '0912345678' LIMIT 1
),
vehicle_assignment_seed AS (
  INSERT INTO route_plan_vehicle_assignments (
    route_plan_id,
    external_vehicle_id,
    assignment_status,
    vehicle_code_snapshot,
    vehicle_plate_snapshot,
    vehicle_type_snapshot,
    vehicle_capacity_snapshot,
    vehicle_seat_count_snapshot
  )
  SELECT
    plan_seed.id,
    vehicle_seed.id,
    'CONFIRMED',
    vehicle_seed.vehicle_code,
    vehicle_seed.plate_number,
    vehicle_seed.vehicle_type,
    vehicle_seed.capacity,
    vehicle_seed.seat_count
  FROM plan_seed
  CROSS JOIN vehicle_seed
  RETURNING id, route_plan_id
),
driver_assignment_seed AS (
  INSERT INTO route_plan_driver_assignments (
    route_plan_id,
    external_driver_id,
    route_plan_vehicle_assignment_id,
    assignment_status,
    driver_code_snapshot,
    driver_name_snapshot,
    driver_phone_snapshot,
    driver_national_id_snapshot,
    driver_license_no_snapshot,
    driver_license_class_snapshot
  )
  SELECT
    vehicle_assignment_seed.route_plan_id,
    driver_seed.id,
    vehicle_assignment_seed.id,
    'CONFIRMED',
    driver_seed.driver_code,
    driver_seed.full_name,
    driver_seed.phone,
    driver_seed.national_id,
    driver_seed.license_no,
    driver_seed.license_class
  FROM vehicle_assignment_seed
  CROSS JOIN driver_seed
  RETURNING route_plan_id
)
INSERT INTO route_plan_customers (
  route_plan_id,
  external_customer_id,
  sequence_no,
  customer_code_snapshot,
  customer_name_snapshot,
  customer_phone_snapshot,
  pickup_address_snapshot,
  dropoff_address_snapshot,
  note
)
SELECT
  plan_seed.id,
  customer_seed.id,
  customer_seed.seq,
  customer_seed.customer_code,
  customer_seed.full_name,
  customer_seed.phone,
  customer_seed.default_pickup_address,
  customer_seed.default_dropoff_address,
  CASE WHEN customer_seed.seq = 1 THEN 'Khách ưu tiên đón trước' ELSE 'Khách đi cùng chuyến' END
FROM plan_seed
CROSS JOIN customer_seed;

INSERT INTO route_plan_logs (route_plan_id, event_type, message, payload, created_by)
SELECT id, 'CREATE_PLAN', 'Tạo kế hoạch điều phối demo', NULL, 'dieuphoi1'
FROM route_plans
WHERE plan_code = 'RP0001';

SELECT COUNT(*) AS so_tai_khoan FROM TaiKhoanNguoiDung;
SELECT COUNT(*) AS so_nhan_vien_dieu_phoi FROM NhanVienDieuPhoi;
SELECT COUNT(*) AS so_tai_xe FROM TaiXe;
SELECT COUNT(*) AS so_xe_trung_chuyen FROM XeTrungChuyen;
SELECT COUNT(*) AS so_khach_hang FROM KhachHang;
SELECT COUNT(*) AS so_ve_trung_chuyen FROM VeTrungChuyen;
SELECT COUNT(*) AS so_lo_trinh_trung_chuyen FROM LoTrinhTrungChuyen;
SELECT COUNT(*) AS so_chi_tiet_lo_trinh FROM ChiTietLoTrinh;
SELECT COUNT(*) AS so_external_customers FROM external_customers;
SELECT COUNT(*) AS so_external_drivers FROM external_drivers;
SELECT COUNT(*) AS so_external_vehicles FROM external_vehicles;
SELECT COUNT(*) AS so_route_plans FROM route_plans;

COMMIT;
